apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-generator
  template:
    metadata:
      labels:
        app: policy-generator
    spec:
      containers:
      - name: generator
        image: pod-security-generator
        imagePullPolicy: Never
        ports:
        - containerPort: 5000